### ISSUE TITLE
Tests fail with error

### ISSUE THREAD

**Issue by kevinburke** [aceakash/project-name-generator#4]
Reproduce with the following steps:

1) check out repository
2) `npm install` 
3) `npm test`

I get the following stack trace:

```
$ npm test

> project-name-generator@2.1.1 test /Users/kevin/code/project-name-generator
> gulp test

(node:14787) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[10:18:03] Using gulpfile ~/code/project-name-generator/gulpfile.js
[10:18:03] Starting 'test'...
[10:18:03] 'test' errored after 14 ms
[10:18:03] Error: Cannot find module '../node_modules/jasmine-core/lib/jasmine-core/jasmine.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kevin/code/project-name-generator/node_modules/minijasminenode2/lib/index.js:5:22)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
npm ERR! Test failed.  See above for more details.
```

I'm using npm 3. I think minijasminenode2 is expecting a different file hierarchy for the node_modules directory.

**Comment by kevinburke** [comment]
Tests run just fine when the project is installed with npm 2

```
$ npm test

> project-name-generator@2.1.1 test /Users/kevin/code/project-name-generator
> gulp test

(node:15205) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[10:21:10] Using gulpfile ~/code/project-name-generator/gulpfile.js
[10:21:10] Starting 'test'...
......................

22 specs, 0 failures
Finished in 0.011 seconds
[10:21:10] Finished 'test' after 109 ms
```

**Comment by aceakash** [comment]
Should be fixed by 0e1cfce
Works in node v4.0.0 (npm v2.14.2)
